# Generated by Django 2.2.7 on 2019-11-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Справочник специализаций',
                'ordering': ('name',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CrashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('specs', models.ManyToManyField(related_name='crash_types', to='lists.Spec', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Тип аварии',
                'verbose_name_plural': 'Справочник типов аварии',
                'ordering': ('name',),
                'default_permissions': (),
            },
        ),
    ]
